name: 'Deploy GCP Workflow'
description: 'Deploy GCP workflow definition'
author: 'Uri Katsir'
branding:
  icon: 'upload-cloud'  
  color: 'blue'
inputs:
  project-id:  # id of the project to use
    description: 'This project will be used to deploy the workflow'
    required: true
    default: ''
  workflow-name:  # workflow-name
    description: 'workflow-name'
    required: true
    default: ''
  workflow-definition-file-name:  # workflow-definition-file-name
    description: 'workflow-definition-file-name'
    required: true
    default: ''
  service-account-name:  # service-account-name
    description: 'service-account-name'
    required: true
    default: '' 
  workflow-region:  # workflow-region
    description: 'workflow-region'
    required: true
    default: 'us-central1'    

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud  
      uses: google-github-actions/auth@v0  
      with:  
        workload_identity_provider: 'projects/854735162550/locations/global/workloadIdentityPools/github-pool/providers/my-provider'  
        service_account: ${{ inputs.service-account-name }}
    - name: Set up gcloud SDK  
      uses: google-github-actions/setup-gcloud@v0     
    - run: gcloud workflows deploy ${{ inputs.workflow-name }} --source=${{ inputs.workflow-definition-file-name }} --service-account=${{ inputs.service-account-name }} --project ${{ inputs.project-id }} --location ${{ inputs.workflow-region }}
      shell: bash
    # - run: gcloud workflows deploy ${{ inputs.workflow-name }} --source=${{ inputs.workflow-definition-file-name }} --project ${{ inputs.project-id }} --location ${{ inputs.workflow-region }}
    #   shell: bash
    
