name: 'Deploy Workflow'
description: 'Deploy GCP workflow definition'
inputs:
  project-id:  # id of the project to use
    description: 'This project will be used to deploy the workflow'
    required: true
    default: ''
  workflow-name:  # workflow-name
    description: 'workflow-name'
    required: true
    default: ''
  workflow-definition-file-name:  # workflow-definition-file-name
    description: 'workflow-definition-file-name'
    required: true
    default: ''
  service-account-name:  # service-account-name
    description: 'service-account-name'
    required: true
    default: '' 
  workflow-region:  # workflow-region
    description: 'workflow-region'
    required: true
    default: 'us-central1'    
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - run: gcloud workflows deploy ${{ inputs.workflow-name }} --source=${{ inputs.workflow-definition-file-name }} --service-account=${{ inputs.service-account-name }} --project ${{ inputs.project-id }} --location ${{ inputs.workflow-region }}
      shell: bash
    # - id: random-number-generator
    #   run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #   shell: bash