# This is a basic workflow to help you get started with Actions

name: Deploy to CloudRun

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "BuildDeployCloudRun"
  BuildDeployCloudRun:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: uri-test
          service_account_key: ${{ secrets.gcp }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Deploy workflow
        uses: UriKatsirPrivate/deploy-workflow@master
        with:
          project_id: uri-test
          workflow-name: deploy-workflow-demo
          workflow-definition-file-name: deploy-workflow-demo.yaml
          service-account-name: workflows-sa@uri-test.iam.gserviceaccount.com
          workflow-region: us-central1 

      
 

       
